def Cuadrado ():
    print("Cuadrado")
    print("+"+ 10 *"-"+"+")
    print(("|"+ " "* 10 + "|\n")*3, end="")
    print("+"+ 10*"-"+"+")  

def Rectangulo ():
    print("Rectangulo")
    print("+"+ 20 *"-"+"+")
    print(("|"+ " "*20  + "|\n")*2, end="")
    print("+"+ 20*"-"+"+")  

def Triangulo ():
    print("Triangulo")
    print(" "*7 + "*")
    print(" "*6 + "*"*3 + " "*1)
    print(" "*5 + "*"*5 + " "*1)
    print(" "*4 + "*"*7 + " "*1)
    print(" "*3 + "*"*9 + " "*1)

def Rombo ():
    print("Rombo")
    print(" "*7 + "*")
    print(" "*6 + "*"*3 + " "*1)
    print(" "*5 + "*"*5 + " "*1)
    print(" "*4 + "*"*7 + " "*1)
    print(" "*3 + "*"*9 + " "*1)
    print(" "*4 + "*"*7 + " "*1)
    print(" "*5 + "*"*5 + " "*1)
    print(" "*6 + "*"*3 + " "*1)
    print(" "*7 + "*")